name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install wasi-sdk
        run: |
          wget --no-verbose 'https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz'
          tar xf wasi-sdk-12.0-linux.tar.gz
          rm wasi-sdk-12.0-linux.tar.gz
          echo "$(pwd)/wasi-sdk-12.0/bin" >> $GITHUB_PATH
      - name: Install binaryen
        run: |
          wget --no-verbose 'https://github.com/WebAssembly/binaryen/releases/download/version_105/binaryen-version_105-x86_64-linux.tar.gz'
          tar xf binaryen-version_105-x86_64-linux.tar.gz
          rm binaryen-version_105-x86_64-linux.tar.gz
          echo "$(pwd)/binaryen-version_105/bin" >> $GITHUB_PATH
      - name: Build
        run: ./build.sh
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build
          single-commit: true
